@startchen
left to right direction

entity Drivers {
    id                  <<key>>
    name
    driver_number       <<multi>>
    nationality
    team_id
}

entity Races {
  id              <<key>>
  season
  date
  circuit_name
  race_type
  country
  city
}

entity Results {
  result_id  <<key>>
  race_id  <<derived>>
  driver_number  <<derived>>
  position 
  points 
}

relationship has{

}
relationship contains{

}


has -(1,n)- Drivers
has -(1,n)- Results

contains -(n,1)- Races
contains -(n,1)- Results


@endchen