@startuml
entity "Drivers" {
  *driver_id : VARCHAR <<PK>>
  --
  name : VARCHAR
  driver_number : INT <<UNIQUE>>
  nationality : VARCHAR
  team_id : VARCHAR <<FK>>
}

entity "Race" {
  *race_id : VARCHAR <<PK>>
  --
  date: DateTime
  circuit_name: String
  race_type: String
  country: String
  city: String
}

entity "Results" {
  *result_id : VARCHAR <<PK>>
}


' Relationships
Drivers ||--o{ Results : "has"
Race }o-|| Results : "contains"
@enduml